
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { MenuProvider } from "@/context/menuContext";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spotify - Clone",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Spotify_icon.svg/232px-Spotify_icon.svg.png"></link>
      </head>
      <body className={`${inter.className} bg-spotify-gray min-h-screen text-gray-300`}>
        <MenuProvider>
          <Header />
          <Sidebar />
        </MenuProvider>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
